### PR TITLE
Fix missing docs (#1172)

### PR DESCRIPTION
**Pull request by BerkhanBerkdemir**
This PR fixes issue #1172. Please see issue as the description of this PR.

### CODE REVIEW

**Comment by composerinteralia** [comment]
Looks reasonable to me. I’m out this week, but will try to get this through when I get back next week.

**Comment by composerinteralia** [comment]
The problem with #1183 is that it links to the version of the file on `master`, rather than the version of the file associated with the specific gem version. What you have in this PR should be enough to fix the problem, since `GETTING_STARTED.md` is listed in `.yardopts`. I will be sure to test this out before merging.

**Comment by composerinteralia** [comment]
This change seems good to me. There is still some inconsistency with the way we link to things (see the links for NAME.md and LICENSE as compared to GETTING_STARTED.md), but I think we can clean those up later.

**Comment by BerkhanBerkdemir** [comment]
@composerinteralia [the link](https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md) still doesn't work :sob:

**Comment by composerinteralia** [comment]
I haven't put together a release yet, so it makes sense that it doesn't work. I'll try to do it soon!

**Pull request merged**
