### PR TITLE
Prepare for factory_bot 6

### LINKED ISSUE #1336: factory_bot 6 checklist
- [x] Remove Rails 4.2 from test matrix
- [x] Remove EOL ruby versions from test matrix
- [x] Remove Rails 4.2 logic from features/support/factories.rb
- [x] Remove deprecated methods from lib/factory.rb
- [x] Bump FactoryBot::Deprecation to 7.0

### PR DESCRIPTION
**Pull request by composerinteralia**
Closes #1336

- removes all the deprecated methods
- removes Ruby 2.3, 2.4 and Rails 4.2 from travis
- `bundle update`s the test gemfiles
- Removes some pre-5.0 logic from a test helper
- Targets Ruby 2.5 with rubocop and fixes violations

We could also remove support for Rails 5.0 and 5.1, which are now EOL, but I don't see a strong reason to do that. We don't seem to have to do anything special to support those versions.

### CODE REVIEW

**Comment by composerinteralia** [comment]
I expect CI to fail because of https://github.com/rubygems/rubygems/pull/3040

**Comment by composerinteralia** [comment]
That’s definitely possible. Do you know if there is anything we need to do in particular besides add 2.7 to Travis? Are we getting keyword argument warnings or anything like that?

**Comment by composerinteralia** [comment]
True. I was thinking about leaving those in for now because there doesn't seem to be any additional maintenance required to do so.

**Comment by nijikon** [comment]
@composerinteralia would you consider dropping `activesupport` dependency in version 6?

**Comment by composerinteralia** [comment]
@nijikon this was discussed in https://github.com/thoughtbot/factory_bot/issues/903. If things have changed significantly since then, we can reopen that issue to discuss again.

**Pull request merged**
