### PR TITLE
Raise helpful error when block given to association

### PR DESCRIPTION
**Pull request by jaredbeck**
> Arguably, association should raise and let the developer know
> they're using it in an unexpected way. I'd love to see a PR for
> that (with a test!), so if you're interested in contributing that,
> please do!
> https://github.com/thoughtbot/factory_girl/issues/1032#issuecomment-329297006

### CODE REVIEW

**Comment by geoffharcourt** [comment]
This looks great!

Could we rename the constant with the error message with a name that doesn't contain a abbreviation or a shortening of words? `ASSOCIATION_BLOCK_ERROR_MESSAGE` or something along those lines?

**Comment by jaredbeck** [comment]
> This looks great!

Thanks.

> Could we rename the constant with the error message with a name that doesn't contain a abbreviation or a shortening of words? ASSOCIATION_BLOCK_ERROR_MESSAGE or something along those lines?

I don't have strong opinions about naming. Whatever the maintainers want to call it is fine with me.

**Comment by composerinteralia** [comment]
I know it has been a while, so I can take over this branch if you are no longer interested in working on it, but my preference would be to add a new error class to `lib/factory_bot/errors.rb` and raise that. It would be nice also to include the name of the association (`name`) and the factory (`@definition.name`) in the error message.

**Comment by bf4** [comment]
https://github.com/thoughtbot/factory_bot/blob/master/NEWS.md#500-february-1-2019

> Changed: Passing a block when defining associations now raises an error

ref https://github.com/thoughtbot/factory_bot/commit/bfeec78f297e2f1b796568d3bba0f4ee7320454c

Screen Shot 2020-02-18 at 9 51 29 AM

breaks on loading.. would be nice to have an optional deprecation to find these things

This is what I did

Gemfile

```diff
-  gem "factory_bot_rails"
+  gem "factory_bot_rails", require: false
```

spec/support/gems/factory_bot.rb

```diff
 require 'factory_bot'

+require 'factory_bot/definition_proxy'

+module FactoryBot
+  class DefinitionProxy
+    def association(name, *options)
+      if block_given?
+        colorizer = ::RSpec::Core::Formatters::ConsoleCodes
+        error_message = "ERROR: FactoryBot AssociationDefinitionError:" \
+            "Unexpected block passed to '#{name}' association "\
+            "in '#{@definition.name}' factory"
+        RSpec.configuration.reporter.message colorizer.wrap(error_message, :failure)
+        declaration = Declaration::Association.new(name, *options)
+        @definition.declare_attribute(declaration)
+        # raise AssociationDefinitionError.new(
+        #   "Unexpected block passed to '#{name}' association "\
+        #   "in '#{@definition.name}' factory"
+        # )
+      else
+        declaration = Declaration::Association.new(name, *options)
+        @definition.declare_attribute(declaration)
+      end
+    end
+  end
+end
+
+require 'factory_bot_rails'
+
 RSpec.configure do |config|
   config.include FactoryBot::Syntax::Methods
 end
```

**Pull request closed without merging**
