### PR TITLE
Support uuids in build_stubbed

### LINKED ISSUE #1498: `build_stubbed` does not fill `id` for `uuid` column type
### Description

When using `uuid` as the primary key type, they `build_stubbed` method does not automatically fill the `id` column. I would assume that this is filled independent of the column type.

### Reproduction Steps

<details>
<summary>Reproduction script</summary>

```ruby
#!/usr/bin/env ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 6.0"
  gem "activerecord"
  gem "pg"
end

require "active_record"
require "factory_bot"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "factory_bot_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  enable_extension 'pgcrypto'

  create_table :int_posts, force: true do |t|
    t.string :body
  end

  create_table :uuid_posts, id: :uuid, force: true do |t|
    t.string :body
  end
end

class IntPost < ActiveRecord::Base
end

class UuidPost < ActiveRecord::Base
end

FactoryBot.define do
  factory :int_post do
    body { "Post body" }
  end

  factory :uuid_post do
    body { "Post body" }
  end
end

class FactoryBotTest < Minitest::Test
  def test_working_with_int
    post = FactoryBot.build_stubbed(:int_post)
    refute_nil post.id
  end

  def test_failing_with_uuid
    post = FactoryBot.build_stubbed(:uuid_post)
    refute_nil post.id
  end
end

# Run the tests with `ruby <filename>`
```

</details>

### Expected behavior

When you use `build_stubbed`, the primary key is always set. Also if you use the `uuid` type.

### Actual behavior

The `id` of the generated instance is `nil`.

### System configuration
**factory_bot version**:  `6.2.0`
**rails version**:  `6.1.3.2`
**ruby version**: `3.0.1`

### PR DESCRIPTION
**Pull request by jaynetics**
This is based on #1514 and fixes #1498.

The only things i did, compared to #1514, are the following:

- rebased on main
- added one more guard clause, to ensure that the worst-case result if the relevant rails API is ever removed is the same lack of UUID support that we have currently

The relevant rails API hasn't changed since PR #1514 was created 2 years ago. It would be nice to finally get support for UUIDs. 😊

### CODE REVIEW

**Comment by mike-burns** [comment]
Right, and we're going to need this now that [we've outlawed setting the `id` explicitly](https://github.com/thoughtbot/factory_bot_rails/pull/419).

The thing I've been staring at all afternoon, though, is: this is all very ActiveRecord-specific, which means it should go in `factory_bot_rails` instead. But I think the original sin was adding this stub strategy to the non-Rails repo in the first place.

OK, I think the plan is: merge this PR, then work on moving the stub strategy into f_b_rails. That will require a lot of finesse and delicacy because I don't want to break any existing code in the process.

Thanks for listening as I talk this through.

Hey @jaynetics @alexandreruban and @StefSchenkelaars , thank you all for the work you put into this!

**Review by mike-burns — APPROVED** [review]

**Comment by mike-burns** [comment]
(Current status: figuring out why CI isn't running. _sigh_)

**Comment by MatheusRich** [comment]
@mike-burns might be related https://github.com/thoughtbot/factory_bot/pull/1593

**Comment by mike-burns** [comment]
Thanks for being on top of things, @MatheusRich! But if that's the case, why aren't those CI checks running?

**Comment by mike-burns** [comment]
I pushed this branch to the main repo and watched CI pass: https://github.com/thoughtbot/factory_bot/actions/runs/6592716225

Going to merge bypassing CI for this PR.

**Comment by jaynetics** [comment]
@mike-burns thanks for merging!

> this is all very ActiveRecord-specific, which means it should go in factory_bot_rails instead. But I think the original sin was adding this stub strategy to the non-Rails repo in the first place.
> OK, I think the plan is: merge this PR, then work on moving the stub strategy into f_b_rails.

if you want to support `build_stubbed` for ORMs other than `activerecord` in the future, a consistent solution might be easier to achieve if its all in the same base repo.

either way, `f_b_rails` doesn't seem quite the right place for it because some people use `activerecord` without rails (e.g. on `sinatra`), and some people use rails without `activerecord` (e.g. using `sequel` instead). currently, `f_b_rails` crashes if rails is not present (despite having only `activerecord`, not `rails`, in its gemspec dependencies), so moving features to there might affect a few people.

**Comment by mike-burns** [comment]
Yeah fair - perhaps the actual original problem was splitting out a Rails-specific gem to begin with, with all the vagueness that "Rails" implies.

**Pull request merged**
